#!/usr/bin/env bash
# Build the Rust ROS nodes (e.g. `adapter`) inside the Jazzy dev image.
#
# This assembles the rosidl_rust toolchain, builds the message packages and
# their Rust crates, registers them for colcon-ros-cargo, then builds the node
# crates. Run it inside the dev container (`.devcontainer`, or `make ros`), or in
# a Jazzy CI job with Rust + colcon-cargo installed.
#
#   docker compose -f docker/dev/compose.yaml run --rm dev \
#     bash docker/dev/build_ros_rust.sh
#
# It writes `ros2_ws/.cargo/config.toml` pointing at the generated interface
# crates so rust-analyzer can resolve the node crates in the container.
#
# NOTE: no `set -u`; ROS setup scripts reference unbound variables.
set -eo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
WS="${ROS_RUST_WS:-/tmp/ros_rust_ws}"

# The workspace / cargo registry are named volumes; a fresh volume can be
# root-owned. Fix ownership with passwordless sudo when needed (no-op in CI/root
# or once it is already owned by the current user).
ensure_writable() {
  local dir="$1"
  if [ ! -d "$dir" ]; then
    mkdir -p "$dir" 2>/dev/null || sudo mkdir -p "$dir"
  fi
  if [ "$(stat -c %U "$dir" 2>/dev/null)" != "$(id -un)" ] \
     && command -v sudo >/dev/null 2>&1; then
    sudo chown -R "$(id -un):$(id -gn)" "$dir" || true
  fi
}
ensure_writable "$WS"
[ -n "${CARGO_HOME:-}" ] && ensure_writable "$CARGO_HOME"

# shellcheck disable=SC1091
source /opt/ros/jazzy/setup.bash

mkdir -p "$WS/src"
clone() { [ -d "$WS/src/$2" ] || git clone --quiet --depth 1 -b "$1" "$3" "$WS/src/$2"; }

[ -d "$WS/src/rosidl_rust" ] || \
  git clone --quiet --depth 1 https://github.com/ros2-rust/rosidl_rust.git "$WS/src/rosidl_rust"
clone jazzy unique_identifier_msgs https://github.com/ros2/unique_identifier_msgs.git
clone jazzy rcl_interfaces https://github.com/ros2/rcl_interfaces.git
clone jazzy rosidl_core https://github.com/ros2/rosidl_core.git
clone jazzy rosidl_defaults https://github.com/ros2/rosidl_defaults.git
clone jazzy common_interfaces https://github.com/ros2/common_interfaces.git

rm -rf "$WS/src"/device_interfaces "$WS/src"/task_interfaces \
       "$WS/src"/perception_interfaces "$WS/src"/diagnosis_interfaces
cp -r "$REPO_ROOT"/ros2_ws/src/robot/interfaces/* "$WS/src/"

cd "$WS"
colcon build --merge-install --packages-up-to \
  rosidl_generator_rs geometry_msgs sensor_msgs \
  device_interfaces task_interfaces perception_interfaces diagnosis_interfaces

# shellcheck disable=SC1091
source install/setup.bash
bash "$REPO_ROOT/ros2_ws/scripts/register_rust_packages.sh" "$WS/install"

# colcon-ros-cargo writes a `.cargo/config.toml` (absolute container paths)
# into the cwd and runs cargo from each package dir, which merges the configs
# on the way up. Keep the node-scoped one out of the way during the build,
# then remove colcon's afterwards and install a ros2_ws-scoped config below.
rm -rf "$REPO_ROOT/ros2_ws/.cargo" "$REPO_ROOT/.cargo"
cd "$REPO_ROOT"
colcon --log-base "$WS/log_nodes" build --merge-install \
  --base-paths \
    "$REPO_ROOT/ros2_ws/src/robot/adapter" \
    "$REPO_ROOT/ros2_ws/src/robot/orchestrator" \
    "$REPO_ROOT/ros2_ws/src/robot/physio_mock" \
    "$REPO_ROOT/ros2_ws/src/robot/diagnosis_node" \
    "$REPO_ROOT/ros2_ws/src/robot/perception_sim" \
    "$REPO_ROOT/ros2_ws/src/robot/perception_camera" \
    "$REPO_ROOT/ros2_ws/src/robot/gateway_bridge" \
  --build-base "$WS/build_nodes" --install-base "$WS/install_nodes"

# Publish a ros2_ws-scoped `[patch.crates-io]` so rust-analyzer and cargo can
# resolve the rosidl-generated interface crates from inside the container,
# while the root (services) workspace stays untouched. Scoped under ros2_ws so
# a host-side `cargo test --workspace` never sees the container paths.
#
# colcon already generated a complete config at the repo root (covering both
# /ws/install and /opt/ros/jazzy crates); reuse it verbatim rather than
# hand-writing a subset that could miss system message crates.
mkdir -p "$REPO_ROOT/ros2_ws/.cargo"
if [ -f "$REPO_ROOT/.cargo/config.toml" ]; then
  cp "$REPO_ROOT/.cargo/config.toml" "$REPO_ROOT/ros2_ws/.cargo/config.toml"
else
  {
    echo "# Generated by docker/dev/build_ros_rust.sh; do not edit."
    echo "[patch.crates-io]"
    declare -A seen=()
    for base in "$WS/install" /opt/ros/jazzy; do
      for d in "$base"/share/*/rust; do
        [ -d "$d" ] || continue
        pkg="$(basename "$(dirname "$d")")"
        [ -n "${seen[$pkg]:-}" ] && continue
        seen[$pkg]=1
        echo "$pkg = { path = \"$d\" }"
      done
    done
  } > "$REPO_ROOT/ros2_ws/.cargo/config.toml"
fi
rm -rf "$REPO_ROOT/.cargo"

echo "[OK] Rust ROS nodes built into $WS/install_nodes"
