<?xml version="1.0"?>
<package format="3">
  <name>mock_exec_layer</name>
  <version>0.1.0</version>
  <description>Deterministic mock execution action server.</description>
  <maintainer email="puranlai@qq.com">Duck Ran</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>builtin_interfaces</depend>
  <depend>rclpy</depend>
  <depend>ros_interfaces</depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
