[package]
name = "orchestration-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
platform = { path = "../platform" }
thiserror.workspace = true

[dev-dependencies]
futures-core.workspace = true
serde_json.workspace = true
