<?xml version="1.0"?>
<package format="3">
  <name>sensor</name>
  <version>0.1.0</version>
  <description>Sensor service crate.</description>
  <maintainer email="puranlai@qq.com">Duck Ran</maintainer>
  <license>Apache-2.0</license>
  <depend>platform</depend>
  <export><build_type>ament_cargo</build_type></export>
</package>
