[package]
name = "perception_sim"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "perception_sim"
path = "src/main.rs"

[dependencies]
rclrs = "0.7"
anyhow = "1"
world-model = { path = "../../../../services/world-model" }
perception-sim = { path = "../../../../services/perception-sim" }
perception_interfaces = { version = "0.1" }
device_interfaces = { version = "0.1" }
geometry_msgs = "*"
builtin_interfaces = "*"
