[package]
name = "adapter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "adapter"
path = "src/main.rs"

[dependencies]
rclrs = "0.7"
anyhow = "1"
serde_json = "1"
futures-timer = "3"
device-sdk = { path = "../../../../services/device-sdk" }
orchestrator-core = { path = "../../../../services/orchestrator-core" }
device_interfaces = { version = "0.1" }
task_interfaces = { version = "0.1" }
geometry_msgs = "*"
builtin_interfaces = "*"
