<?xml version="1.0"?>
<package format="3">
  <name>ros_sensor_client</name>
  <version>0.1.0</version>
  <description>Typed Rust ROS physiological sensor subscriber.</description>
  <maintainer email="puranlai@qq.com">Duck Ran</maintainer>
  <license>Apache-2.0</license>
  <depend>rclrs</depend>
  <depend>physio_interfaces</depend>
  <depend>platform</depend>
  <export><build_type>ament_cargo</build_type></export>
</package>
